### ISSUE TITLE
[NEW] Date time picker

### ISSUE THREAD

**Issue by hnandarusdy** [apollo-forms/mantra-react-form-builder#10]
We need a feature of date time picker. What we have right now is only date picker.

**Comment by danutc** [comment]
from sprint 3 and work started by Roman

**Comment by xcomanche** [comment]
Completed here: https://github.com/xcomanche/mantra-react-form-builder/commit/48a33e7d20012cf2dd3f5191e226abd164ce974b

Should DateTime contain some default values? Maybe format, according to moment.js specification.

**Comment by xcomanche** [comment]
@bubuzzz  suggested to fix issue with closing DateTime Picket, when user selects date.
To do that i'll use fork of the react-datetime-picker, which actually already had that issue fixed.

**Comment by xcomanche** [comment]
Changes from @bubuzzz implemented here: https://github.com/xcomanche/mantra-react-form-builder/commit/ade03e20f60e0070b76baa47d0d20369608bb89e

**Comment by hnandarusdy** [comment]
All looks good, last thing, could you please re-style datetime picker to be like this: 
![image](https://cloud.githubusercontent.com/assets/14065403/17234298/dddf3d34-557a-11e6-81c8-775274abbf6c.png)

**Comment by xcomanche** [comment]
@hnandarusdy is this high priority right now? if yes, i could spend some time on it.
But i could suggest to close this one, and open new issue: for restyling, and push it to next sprint. Because if i'll spend time today on restyling of this one, i won't be able to finish on time dynamic fields (https://github.com/apollo-forms/mantra-react-form-builder/issues/15)

**Comment by hnandarusdy** [comment]
Ok. I will create separate issue for this
