### ISSUE TITLE
Payment status widget

### ISSUE THREAD

**Issue by bubuzzz** [apollo-forms/mantra-react-form-builder#18]
We need to have a sample payment status widget with the following operations: 
1st textbox – total
2nd textbox - balance
3rd textbox – result
checkbox – purchase Order
Flow:
-       if Purchase Order is true hide Total, Balance
-       Check on purchase Order -> result : “Purchase order”
-       Uncheck on purchase order and key in total and balance

o   Result "Payment in full" when Balance == 0
o   Result "No payment received" when Balance == 0 && total == 0
o   Result "Partial payment greater than 50%" when balance/total <= 50%
o   Result "Partial payment less than 50%" when balance/total > 50%

**Comment by danutc** [comment]
this should be already done by Roman; needs testing on feature branch

Implemented PaymentStatus custom field as a widget  (implemented here: https://github.com/xcomanche/mantra-react-form-builder/tree/feature/custom_payment_status_field)

**Comment by bubuzzz** [comment]
@danutc currently, widget is only shown on the page but data cannot be submitted the data. need to enhance.
@xcomanche I updated the text a bit on the issue description. Please change accordingly. I think we should disable the edit panel for the composite widget, thus it does not make sense to show the panel (properties panel should belong to one single component i guess)

**Comment by rkxtd** [comment]
@bubuzzz okay, i'll update this one in my feature branch

**Comment by xcomanche** [comment]
Oh, sorry, that was me, just logged with different login.

**Comment by xcomanche** [comment]
@bubuzzz I'm working on two issues here:
1. Gather data on form submit - don't have a questions here, as i understood on submit form object should contain all data entered into fields as Input_XXXX object. where XXXX - is a random number generated for a field on creation stage

2. turn off editing. - here i have a question. So far as i can see,  all our field created as editable_fields. So it's possible to have two possible implementations: Extend editable field to contain property: editable:false(or similar), in this case we want have editable icon, and double click also will not open editor. Or second possible solution, Create not_editable_field component and extend custom_payment_field from this component. (which want have editable functionality at all). I prefer second option, and it could be already implemented in form_builder

**Comment by xcomanche** [comment]
@bubuzzz 
1. gathering data is already working, for Wysiwyg editor. For payment status field i'm receiving some strange error. Because i'm trying to return object from the PaymentStatus field. In case we will return string - it works fine. It's a matter of convention, what we want to return from that field. Let's have a chat today evening to talk about that

2. I removed editSchema from paymentStatus field. And extended form_editable_field to support that. From now on if field doesn't have specified editSchema, in that case row will be generated without editable component.

**Comment by hnandarusdy** [comment]
@xcomanche 
I did a testing on payment status widget, and here is my feedback:

1. When I click 'Purchase order', it is not checked visually
![image](https://cloud.githubusercontent.com/assets/14065403/17196012/ecce0900-54a4-11e6-8f51-c5c4c9535835.png)

2. Please rename 'result' to 'Payment status'. We also don't need label 'Payment status' on the top

3. Please follow payment status to description, explained by Thai. for example: 
- Part payment greater than 50  --> (should be) Partial payment less than 50%, etc....

4. Please make a default value for Total = 0 and Balance = 0, also these fields should only accept number, would be better if you could convert these fields to currency type.

5. Default value of payment status (currently we call it 'result') = No payment received

6. The calculation is wrong. 
Test scenario: 
Total = 1000
Balance = 500
Expected Result: Partial payment greater than 50%. 
Actual Result : Partial payment less than 50%

7. The payment status doesn't look good. Perhaps, it would be better to use bootstrap component? and also make payment status on another line and purchase order on the top, while keep **total and balance in the same line**. 

As your reference in our current system: 
![image](https://cloud.githubusercontent.com/assets/14065403/17196277/ca93f10e-54a6-11e6-9581-958ffd74e372.png)

8. Disable text box for payment status so that users can't change it

**Comment by xcomanche** [comment]
@hnandarusdy i pushed changes for all mentioned issues. Please verify

**Comment by hnandarusdy** [comment]
did a testing on payment status widget, and here is my feedback:

DONE
====================================================
**DONE** - 1. When I click 'Purchase order', it is not checked visually 
**DONE** - Please rename 'result' to 'Payment status'. We also don't need label 'Payment status' on the top
**DONE** - Default value of payment status (currently we call it 'result') = No payment received
**DONE** - The calculation is wrong. 

To Do
====================================================
Please follow payment status to description, explained by Thai. for example:
- "Purchase **O**rder" --> "Purchase **o**rder" (change 'O' to 'o' for **o**rder)

The widget looks good, the only thing you need to change: 
- It would look better if checkbox is on the left. for example: 
![image](https://cloud.githubusercontent.com/assets/14065403/17233587/51a45698-5574-11e6-94d7-ac0af45e0ad4.png)

- I can't input decimal in both Total and Balance. So please make it available. Probably this can be your reference: http://jsfiddle.net/UEVv6/2/

example value to display: 2,058.60 
value to be stored in database: 2058.60

- I can't delete last digit unless I highlight it and change the value but this is unacceptable because it makes people hard to change the value. 
![image](https://cloud.githubusercontent.com/assets/14065403/17233757/d69a0018-5575-11e6-9809-8db8d09c1397.png)

Please adjust the value return from the widget:
balance:"100", it should be balance:100 (saved as numeric)
purchase:false (Ok)
result:"Partial payment less than 50%" (rename "result" to "paymentStatus")
total:"100"  it should be total:100 (saved as numeric)

**Comment by xcomanche** [comment]
@hnandarusdy did i understood you correct?
I shouldn't stop user from entering anything into the field. But when he done with editing of the number field, the value should be formatted in a correct currency way (showed on example), and returned to the server as usual decimal number with two digits after comma?

**Comment by hnandarusdy** [comment]
On Fri, Jul 29, 2016 at 2:57 PM, Roman Shuvaryk <notifications@github.com>
wrote:

> @hnandarusdy <https://github.com/hnandarusdy> did i understood you
> correct?
> I shouldn't stop user from entering anything into the field. But when he
> done with editing of the number field, the value should be formatted in a
> correct currency way (showed on example), and returned to the server as
> usual decimal number with two digits after comma?
>
> Yup, that is correct,

The value display to user can be 123,456.78 but when he has done it and
click submit for example, the value return to database should be numeric
123456.78. so that I can do aggregate when doing report.
just reminder, default value should be *0*. meaning, when somebody delete
all characters in the field and move the cursor to another field. that
field should be 0 again.

**Comment by xcomanche** [comment]
@hnandarusdy okay, this one is done. please verify

**Comment by hnandarusdy** [comment]
@xcomanche everything looks ok, but Sorry, we forgot to mention 1 more condition regarding payment status. 
payment status: "No payment received" when Balance == 0 && total == 0 OR **balance==total**
